name: Unit Test

on: [push, pull_request]


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: install poetry
        uses: Gr1N/setup-poetry@v4

      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.virtualenvs
          key: poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys:
            poetry-${{ hashFiles('**/poetry.lock') }}

      - name: Config poetry
        run: |
          poetry config virtualenvs.in-project false
          poetry config virtualenvs.path ~/.virtualenvs

      - name: Install packages
        run: poetry install
        if: steps.cache-primes.outputs.cache-hit != 'true'

      - name: test
        run: poetry run pytest
